// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Data Types


The page contains a list of SQL data types available in Ignite such as string, numeric, and date/time types.

Every SQL type is mapped to a programming language or driver specific type that is supported by Ignite natively.

== BOOLEAN
Possible values: TRUE and FALSE.

== BIGINT
Possible values: [`-9223372036854775808`, `9223372036854775807`].

== DECIMAL
Possible values: Exact number of selectable precision.

== DOUBLE
Possible values: A floating point number.

== INTEGER
Possible values: [`-2147483648`, `2147483647`].

== REAL
Possible values: A single precision floating point number.

== SMALLINT
Possible values: [`-32768`, `32767`].

== VARCHAR
Possible values: A Unicode String.

== VARBINARY
Possible values: binary data (“byte array”).

== DATE
Possible values: The date data type. The format is `yyyy-MM-dd`.

== TIME
Possible values: The time data type. The format is `hh:mm:ss`.

== TIMESTAMP
Possible values: The timestamp data type. The format is `yyyy-MM-dd hh:mm:ss[.nnnnnnnnn]`.

== UUID
Possible values: Universally unique identifier. This is a 128 bit value.