// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Distribution Zones

This section describes Apache Ignite 3 distribution zones.

== CREATE ZONE

Creates a new distribution zone.

[source,sql]
----
CREATE ZONE
    { database_name.schema_name.distribution_zone_name | schema_name.distribution_zone_name | distribution_zone_name }
    [WITH
        [
            <data_nodes_auto_adjust> |
            (<data_nodes_auto_adjust>, DATA_NODES_FILTER = filter)
        ],
        [PARTITIONS = partitions],
        [REPLICAS = replicas],
        [AFFINITY_FUNCTION = function]
    ]
[;]
----

Parameters:

* `DATA_NODES_FILTER` -
* `PARTITIONS` -
* `REPLICAS` -
* `AFFINITY_FUNCTION` -



[source,sql]
----
DATA_NODES_AUTO_ADJUST_SCALE_UP = scale_up_value |
DATA_NODES_AUTO_ADJUST_SCALE_DOWN = scale_down_value |
(DATA_NODES_AUTO_ADJUST_SCALE_UP = scale_up_value & DATA_NODES_AUTO_ADJUST_SCALE_DOWN = scale_down_value) | DATA_NODES_AUTO_ADJUST  = auto_adjust_value
----