#!/bin/sh

#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
set -o errexit # Exit on error
set -o nounset # Exit on unset variables

SCRIPT_DIR=$(dirname "$0")

cd ${SCRIPT_DIR} || exit  # SCRIPT_DIR points at bin
cd .. # now SCRIPT_DIR points at parent dir for bin

# if IGNITE_HOME is not set than it will be parent directory for bin
if [ -z ${IGNITE_HOME+x} ]; then IGNITE_HOME=$(pwd); fi


. @CONF_DIR@/@VARS_FILE_NAME@
. ${IGNITE_HOME}/lib/@BOOTSTRAP_FILE_NAME@

cd ${IGNITE_HOME} || exit

start() {
  echo "Starting Ignite 3..."

  STARTUP_LOG_FILE="${LOG_DIR}/ignite3db-startup.log"

  CMD="${JAVA_CMD_WITH_ARGS} ${APPLICATION_ARGS}"
  $CMD >>"${STARTUP_LOG_FILE}" 2>&1 </dev/null & echo $! >${IGNITE_HOME}/pid

  rest_address_file=${WORK_DIR}/rest-address
  max_attempts=30
  count=0
  while [ ! -f "$rest_address_file" ] && [ "$count" -lt "$max_attempts" ]; do
    sleep 1
    count=$((count + 1))
  done

 if [ ! -f "$rest_address_file" ]; then
     echo "Failure: Application did not start within the expected time frame. Check out ${STARTUP_LOG_FILE}" >&2
     exit 1
 else
     rest_address=$(cat "$rest_address_file")
     echo "Node named ${NODE_NAME} started successfully. REST addresses are [$rest_address]"
 fi
}

stop() {
  kill -9 "$(cat ${IGNITE_HOME}/pid)"
  rm ${WORK_DIR}/rest-address
}

case $1 in
start)
  start
  ;;
stop)
  stop
  ;;
restart)
  stop
  start
  ;;
*)
  echo "Unknown command '$1', available commands: start, stop, restart"
  exit 1
  ;;
esac


