// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Apache Ignite 3

== What Is Ignite?

Ignite is a unified real-time platform developed by the company of the same name.

Ignite is a platform that is designed to tackle speed and scale challenges. But
what does that mean? In practice, it signifies that Ignite is capable of storing and processing your data
across a cluster of interconnected machines that are deeply integrated into your environment.

Ignite APIs are developed in a way to minimize network traffic
between cluster nodes and your applications. You can perform both distributed processing and distributed data storage for the applications.