@startuml
title Replicas update stage

database Coordinator as crd
database "Cluster node" as node
queue replicas as replicas

activate crd

crd -> node ++ : MinimumTimesRequest
node -> node
note right
  determine minimum begin time among all
  active RW transactions started locally using
  ActiveLocalTxMinimumRequiredTimeProvider
end note
node -> crd -- : MinimumTimesResponse

crd -> crd : compute global minimum tx time

crd -> node ++ : PrepareUpdateTxBeginTimeMessage
node ->> node
note right
  send local
  UpdateMinimumActiveTxBeginTimeReplicaRequest
  to local primary replicas
end note
node ->> replicas : UpdateMinimumActiveTxBeginTimeCommand
replicas ->> replicas
note right
  publish timestamp when flushing
  of the partition data is completed
end note

@enduml