name: 'Publish Releases'
description: 'Runs gradle tasks to publish versions to Artifactory and GitHub.'
outputs:
  version:
    description: "The version tag this created."
    value: ${{ steps.get-tag.outputs.tag }}
runs:
  using: "composite"
  steps:
    - id: get-tag
      run: echo "::set-output name=tag::$(./gradlew -q getVersion)"
      shell: bash
    - run: echo Got version ${{ steps.get-tag.outputs.tag }}
      shell: bash
    - run: ./gradlew build publishToMavenLocal artifactoryPublish -Partifactory.dryRun
      shell: bash
    - run: ./gradlew ciPerformRelease
      shell: bash
