name: "Publish Releases"
description: "Runs gradle tasks to publish versions to Artifactory and GitHub."

outputs:
  version:
    description: "The version tag this created."
    value: ${{ steps.get-tag.outputs.tag }}

runs:
  using: "composite"
  steps:

    # 1️⃣ Get version from Shipkit
    - id: get-tag
      shell: bash
      run: echo "::set-output name=tag::$(./gradlew -q getVersion)"

    # 2️⃣ Print version
    - shell: bash
      run: |
        echo "Releasing version: ${{ steps.get-tag.outputs.tag }}"

    # 1️⃣ Build & publish artifacts
    - shell: bash
      run: |
        ./gradlew build -x integrationTest artifactoryPublish --no-configuration-cache

    # 2️⃣ GitHub release
    - shell: bash
      run: |
        ./gradlew githubRelease \
        -PprojectVersion=${{ steps.get-tag.outputs.tag }} \
        --no-configuration-cache
