= Configuration Migration

This section describes how to configure a Ignite 2 cluster into which you will migrate all the components of your Ignite 2 cluster.

== Configure the Cluster

You need to configure the cluster you have created to match the Ignite 2 cluster you are migrating from.

While cluster configuration files for Ignite 2 are XML beans, Ignite 3 uses the HOCON format. Moreover, many configuration structures in version 2 are different from those used in version 3.

In Ignite 3, the configuration file has a single root called `ignite`. All configuration sections are children, grandchildren, etc., of that root.

NOTE: In Ignite 3, you can create and maintain the configuration in either JSON or HOCON format. 

For example:

[source, json]
----
{
    "ignite" : {
        "network" : {
            "nodeFinder" : {
                "netClusterNodes" : ["localhost:3344"]
            },
            "port" : 3344
        },
        "storage" : {
            "profiles" : [
                {
                    "name" : "persistent",
                    "engine" : "aipersist"
                }
            ]
        },
        "nodeAttributes.nodeAttributes" : {
            "region" : "US",
            "storage" : "SSD"
        }
    }
}
----

There are two options for creating the required Ignite 3 configuration:

* <<Based on Ignite 2 Configuration>>
* <<From Scratch>>

== Based on Ignite 2 Configuration

To create a Ignite 3 cluster and node configuration HOCON files based on the Ignite 2 configuration XML file, you can use the migration tools:

=== Download and Install Migration Tools

. link:https://dlcdn.apache.org/ignite/3.1.0/migration-tools-cli-3.1.0.zip[Download] the migration tools.
. Unpack the downloaded archive to your machine.
. To explore the available commands in help, run the following command from the migration tools directory:
+
[source, shell]
----
bin/migration-tools --help 
----
+
or
+
[source, shell]
----
bin/migration-tools {command} --help 
----
+
Substitute `{command}` with the actual command name.

=== Update Configuration

For simpler configurations, this tool will be sufficient. All <<Supported Properties>> will be converted to Ignite 3 format, and you will receive warnings for all configuration parameters that were not converted.

Advanced cluster configurations should be remade in Ignite 3 <<From Scratch>> to avoid possible issues.

==== Supported Properties

The migration tool supports the following configuration properties:

* `cacheConfiguration`
* `clientConnectorConfiguration`
* `communicationSpi`
* `dataStorageConfiguration`
* `discoverySpi`
* `sslContextFactory`

Other properties present in the configuration will be ignored.

=== Convert Configuration

To convert the configuration:

[source, shell]
----
bin/migration-tools configuration-converter sourceFile targetNodeConfig targetClusterConfig
----

Where:

* `sourceFile` is the Ignite 2 configuration file.
* `targetNodeConfig` is the node configuration file. This configuration will be applied only to individual nodes.
* `targetClusterConfig` is the cluster configuration file. This configuration will be applied to the entire cluster.

For example:

[source, shell]
----
bin/migration-tools configuration-converter source.xml target-node.conf target-cluster.conf
----

Migration tool will store logs in the `USER_HOME/.ignite-migration-tools/logs` folder by default.
Alternatively, the logs folder can be configured using the `IGNITE_MIGRATION_TOOLS_LOGS_DIR` environment variable.

=== Apply Configuration

==== Node Configuration

You can apply the converted node configuration to the node on startup by replacing the contents of the `etc/ignite-config.conf` file. Only modified configurations are applied, other required parameters will be applied at default values. The default configuration file contains only default values.

==== Cluster Configuration

The newly generated configuration can be applied to the cluster by using the CLI tool.

* Start Ignite 3 nodes as described in the link:quick-start/getting-started-guide[Quick Start];
* When initializing the cluster, provide the :
+
[source, shell]
----
cluster init --name=sampleCluster --license=/license.conf --config-files=target-cluster.conf
----

== From Scratch

Ignite 3 configuration is split between Cluster, Node and distribution zone configurations.

=== Node Configuration

Node configuration stores information about the locally running node.

==== Storage Configuration

Ignite 3 storage is configured in a completely different manner from Ignite 2:

- First, you configure *storage engine* properties, which may include properties like page size or checkpoint frequency.
- Then, you create a *storage profile*, which defines a specific storage that will be used.
- Then, you create a *distribution zone* using the storage profile, which can be further used to fine-tune the storage by defining where and how to store data across the cluster.
- Finally, each *table* can be assigned  to the distribution zone, or directly to a storage profile.

Fore more information about the storage profiles, see link:administrators-guide/storage/storage-overview[Storage Profiles and Engines] and link:administrators-guide/storage/distribution-zones[Distribution Zones].

Note:

- Only tables and distribution zones can be configured from code. Storage profiles and engines must be configured by updating node configuration and restarting node.
- Custom affinity functions are replaced by distribution zones.
- External storage is supported via cache storage that must be configured by using SQL.


==== Client Configuration

All clients in Ignite 3 are "thin", and use a similar `clientConnector` configuration. See link:developers-guide/clients/overview[Ignite Clients] section for more information on configuring client connector.

==== Eviction Policies

Data eviction is performed on volatile storage based on link:administrators-guide/storage/storage-overview[storage engine] configuration.

==== Network Configuration

Node network configuration is now performed in  the `network` section of the link:administrators-guide/config/node-config[node configuration].

==== REST API Configuration

REST API is a significant part of Ignite 3. It can be used for multiple purposes, including cluster and node configuration and running SQL requests.

You can configure REST properties in link:administrators-guide/config/node-config[node configuration].

=== Cluster Configuration

Cluster configuration applies to all nodes in the cluster. It is automatically propagated across the cluster from the node you apply in at.

==== Data Encryption

Transparent data encryption is configured for the whole cluster at once, instead of being done on a per-cluster basis. For information on configuring TDE, see link:administrators-guide/security/tde[Transparent Data Encryption] section.

==== Handling Events

Events configuration is simplified in Ignite 3. It is separated in 2 configurations:

- Event *channels* define what is collected.
- Event *sinks* define where the data is sent.

In the current release, only `log` sink are supported. You can configure events as described in the link:developers-guide/events/overview[Events] section.

==== Metrics Collection

Ignite 3 has metrics disabled by default.

All metrics are grouped according to their metric sources, and are enabled in cluster configuration per metric source.

Then, these metrics will be available in Ignite JMX beans.

For instructions on configuring metrics, see link:administrators-guide/metrics/configuring-metrics[Metrics Configuration].

==== Cluster Security and Authorization

Cluster security and authorization was completely rewritten from the ground up and is not directly comparable with Ignite 2. In Ignite 3:

- If security is enabled, users need a password to log in to the cluster.
- Each user has one or more roles.
- Each role specifies a list of permissions that users with this role can perform.

All security configuration is part of cluster configuration and is shared across all nodes. For more information on configuring security, see link:administrators-guide/security/authentication[Authentication] documentation.
