create table CATALOG_SALES
(
    CS_SOLD_DATE_SK          INTEGER,
    CS_SOLD_TIME_SK          INTEGER,
    CS_SHIP_DATE_SK          INTEGER,
    CS_BILL_CUSTOMER_SK      INTEGER,
    CS_BILL_CDEMO_SK         INTEGER,
    CS_BILL_HDEMO_SK         INTEGER,
    CS_BILL_ADDR_SK          INTEGER,
    CS_SHIP_CUSTOMER_SK      INTEGER,
    CS_SHIP_CDEMO_SK         INTEGER,
    CS_SHIP_HDEMO_SK         INTEGER,
    CS_SHIP_ADDR_SK          INTEGER,
    CS_CALL_CENTER_SK        INTEGER,
    CS_CATALOG_PAGE_SK       INTEGER,
    CS_SHIP_MODE_SK          INTEGER,
    CS_WAREHOUSE_SK          INTEGER,
    CS_ITEM_SK               INTEGER not null,
    CS_PROMO_SK              INTEGER,
    CS_ORDER_NUMBER          INTEGER not null,
    CS_QUANTITY              INTEGER,
    CS_WHOLESALE_COST        NUMERIC(7, 2),
    CS_LIST_PRICE            NUMERIC(7, 2),
    CS_SALES_PRICE           NUMERIC(7, 2),
    CS_EXT_DISCOUNT_AMT      NUMERIC(7, 2),
    CS_EXT_SALES_PRICE       NUMERIC(7, 2),
    CS_EXT_WHOLESALE_COST    NUMERIC(7, 2),
    CS_EXT_LIST_PRICE        NUMERIC(7, 2),
    CS_EXT_TAX               NUMERIC(7, 2),
    CS_COUPON_AMT            NUMERIC(7, 2),
    CS_EXT_SHIP_COST         NUMERIC(7, 2),
    CS_NET_PAID              NUMERIC(7, 2),
    CS_NET_PAID_INC_TAX      NUMERIC(7, 2),
    CS_NET_PAID_INC_SHIP     NUMERIC(7, 2),
    CS_NET_PAID_INC_SHIP_TAX NUMERIC(7, 2),
    CS_NET_PROFIT            NUMERIC(7, 2),
    constraint CATALOG_SALES_PK
        primary key (CS_ITEM_SK, CS_ORDER_NUMBER)
);