create table WEB_RETURNS
(
    WR_RETURNED_DATE_SK      INTEGER,
    WR_RETURNED_TIME_SK      INTEGER,
    WR_ITEM_SK               INTEGER not null,
    WR_REFUNDED_CUSTOMER_SK  INTEGER,
    WR_REFUNDED_CDEMO_SK     INTEGER,
    WR_REFUNDED_HDEMO_SK     INTEGER,
    WR_REFUNDED_ADDR_SK      INTEGER,
    WR_RETURNING_CUSTOMER_SK INTEGER,
    WR_RETURNING_CDEMO_SK    INTEGER,
    WR_RETURNING_HDEMO_SK    INTEGER,
    WR_RETURNING_ADDR_SK     INTEGER,
    WR_WEB_PAGE_SK           INTEGER,
    WR_REASON_SK             INTEGER,
    WR_ORDER_NUMBER          INTEGER not null,
    WR_RETURN_QUANTITY       INTEGER,
    WR_RETURN_AMT            NUMERIC(7, 2),
    WR_RETURN_TAX            NUMERIC(7, 2),
    WR_RETURN_AMT_INC_TAX    NUMERIC(7, 2),
    WR_FEE                   NUMERIC(7, 2),
    WR_RETURN_SHIP_COST      NUMERIC(7, 2),
    WR_REFUNDED_CASH         NUMERIC(7, 2),
    WR_REVERSED_CHARGE       NUMERIC(7, 2),
    WR_ACCOUNT_CREDIT        NUMERIC(7, 2),
    WR_NET_LOSS              NUMERIC(7, 2),
    constraint WEB_RETURNS_PK
        primary key (WR_ITEM_SK, WR_ORDER_NUMBER)
);
