// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Calcite-Based SQL Engine

This Alpha release introduces new SQL engine based on the Apache Calcite framework to parse and optimize queries and generate execution plans. Previously, it was based on H2 Database.

Apache Calcite is a dynamic data management framework, which mainly serves for mediating between applications and one or more data storage locations and data processing engines.
For more information on Apache Calcite, please see the link:https://calcite.apache.org/docs/[product documentation,window=_blank].

Replacing H2 SQL engine with Apache Calcite incorporates the following general improvements:

* *Wider SQL support*: Apache Calcite, unlike H2, is specifically designed for SQL enablement on top of an arbitrary external data storage;
* *Better optimization algorithms*: Apache Calcite optimizes queries by repeatedly applying planner rules to a relational expression;
* *Higher overall performance*: Calcite offers much higher levels of execution flexibility, as well as higher efficiency in terms of both memory and CPU consumption.

== Data Definition Language (DDL)

== CREATE TABLE

Creates a new table.

[source,sql]
----
CREATE TABLE [IF NOT EXISTS] [simpleName | schemaName.simpleName] (tableColumn [, tableColumn]...)
[WITH "paramName=paramValue [,paramName=paramValue]..."]

tableColumn = columnName columnType [[NOT] NULL] [DEFAULT defaultValue] [PRIMARY KEY]
----


Parameters:

* `tableName` - name of the table.
* `tableColumn` - name and type of a column to be created in the new table.
* `DEFAULT` - specifies a default value for the column. Only constant values are accepted.
* `IF NOT EXISTS` - create the table only if a table with the same name does not exist.
* `WITH` - accepts additional parameters not defined by ANSI-99 SQL:

** `Replicas` - sets the number of partition copies, including the master copy.
** `Partitions` - sets the number of table partitions.

image::images/svg/create_table.svg[Embedded,opts=inline]


Examples:

Create Person table:

[source,sql]
----
CREATE TABLE IF NOT EXISTS Person (
  id int primary key,
  city_id int,
  name varchar,
  age int,
  company varchar,
)
----

== ALTER TABLE

Modify the structure of an existing table.

[source,sql]
----
ALTER TABLE [IF EXISTS] tableName {alter_specification}

alter_specification:
    ADD [COLUMN] {[IF NOT EXISTS] tableColumn | (tableColumn [,...])}
  | DROP [COLUMN] {[IF EXISTS] columnName | (columnName [,...])}

tableColumn := columnName columnType
----

Parameters:

- `tableName` - the name of the table.
- `tableColumn` - the name and type of the column to be added to the table.
- `IF EXISTS` - if applied to TABLE, do not throw an error if a table with the specified table name does not exist. If applied to COLUMN, do not throw an error if a column with the specified name does not exist.
- `IF NOT EXISTS` - do not throw an error if a column with the same name already exists.


`ALTER TABLE ADD` adds a new column or several columns to a previously created table. Once a column is added, it can be accessed by using DML commands and indexed with the CREATE INDEX statement.

`ALTER TABLE DROP` removes an existing column or multiple columns from a table. Once a column is removed, it cannot be accessed within queries. Consider the following notes and limitations:

Examples:

Add a column to the table:

[source,sql]
----
ALTER TABLE Person ADD COLUMN city varchar;
----

== DROP TABLE

The `DROP TABLE` command drops an existing table.

[source,sql]
----
DROP TABLE [IF EXISTS] tableName
----

Parameters:

- `tableName` - the name of the table.
- `IF NOT EXISTS` - do not throw an error if a table with the same name does not exist.


Both DDL and DML commands targeting the same table are blocked while the `DROP TABLE` is in progress.
Once the table is dropped, all pending commands will fail with appropriate errors.

Examples:

Drop Person table if the one exists:

[source,sql]
----
DROP TABLE IF EXISTS "Person";
----


== CREATE INDEX

Create an index on the specified table.

[source,sql]
----
CREATE INDEX indexName [[IF NOT EXISTS] indexName] ON tableName (columnName [ASC|DESC] [,...])
----

Parameters:

* `indexName` - the name of the index to be created.
* `ASC` - specifies ascending sort order (default).
* `DESC` - specifies descending sort order.
* `IF NOT EXISTS` - do not throw an error if an index with the same name already exists. The database checks indexes' names only, and does not consider columns types or count.


Examples:

Create a regular index:

[source,sql]
----
CREATE INDEX title_idx ON books (title);
----

Create a descending index only if it does not exist:

[source,sql]
----
CREATE INDEX IF NOT EXISTS name_idx ON persons (firstName DESC);
----


== DROP INDEX

`DROP INDEX` deletes an existing index.


[source,sql]
----
DROP INDEX [IF EXISTS] indexName
----

Parameters:

* `indexName` - the name of the index to drop.
* `IF EXISTS` - do not throw an error if an index with the specified name does not exist. The database checks indexes' names only not considering column types or count.


DDL commands targeting the same table are blocked until `DROP INDEX` is in progress. DML command execution is not affected and can be performed in parallel.

=== Examples

Drop an index:

[source,sql]
----
DROP INDEX idx_person_name;
----


== Data Manipulation Language (DML)

This section walks you through all data manipulation language (DML) commands supported by Apache Ignite Alpha 3.

WARNING: Currently, `WITH` and `MERGE` commands are not supported.

=== SELECT

Retrieves data from a table or multiple tables.

[source,sql]
----
SELECT [ hintComment ] [ STREAM ] [ ALL | DISTINCT ]
    { * | projectItem [, projectItem ]* }
FROM tableExpression
[ WHERE booleanExpression ]
[ GROUP BY { groupItem [, groupItem ]* } ]
[ HAVING booleanExpression ]
----

=== INSERT

Inserts data into a table.

[source,sql]
----
{ INSERT | UPSERT } INTO tablePrimary
[ '(' column [, column ]* ')' ]
query
----

=== UPDATE

Updates data in a table.

[source,sql]
----
UPDATE tablePrimary
SET assign [, assign ]*
[ WHERE booleanExpression ]
----

=== DELETE

Deletes data from a table.

[source,sql]
----
DELETE FROM tablePrimary [ [ AS ] alias ]
[ WHERE booleanExpression ]
----

== Supported Operators and Functions

=== Aggregate Functions

==== COUNT

[source,sql]
----
COUNT( [ ALL | DISTINCT ] value [, value ]*)
----

Returns the number of input rows for which value is not null (wholly not null if value is composite).

==== AVG

[source,sql]
----
AVG( [ ALL | DISTINCT ] numeric)
----

Returns the average (arithmetic mean) of numeric across all input values.

==== SUM

[source,sql]
----
SUM( [ ALL | DISTINCT ] numeric)
----

Returns the sum of numeric across all input values.

==== MIN

[source,sql]
----
MIN( [ ALL | DISTINCT ] value)
----

Returns the minimum value of value across all input values.

==== MAX

[source,sql]
----
MAX( [ ALL | DISTINCT ] value)
----

Returns the maximum value of value across all input values.

==== STRING_AGG

[source,sql]
----
STRING_AGG( value [, separator ] [ ORDER BY ...])
----

Concatenates the values of string expressions and places separator values between them.

==== STRING_CONCAT

[source,sql]
----
STRING_CONCAT(string1, string2, ... stringN)
----

Concatenates the text values in the specified data ranges.


=== Functions


==== JSON

* JSON_EXISTS
* JSON_VALUE
* JSON_QUERY
* JSON_OBJECT
* JSON_ARRAY
* JSON_PRETTY
* STRING
* CHAR_LENGTH
* CHARACTER_LENGTH
* UPPER
* LOWER
* POSITION
* TRIM
* OVERLAY
* SUBSTRING
* INITCAP
* SPACE
* STRCMP
* REVERSE
* REGEXP_REPLACE
* SHA1
* MD5
* LTRIM
* TO_BASE64
* FROM_BASE64
* COMPRESS
* CONCAT
* TRANSLATE
* ASCII
* LEFT
* RIGHT
* REPEAT
* SOUNDEX
* For more information on functions supported by Apache Calcite, see the link:https://calcite.apache.org/docs/reference.html#operators-and-functions[product documentation,window=_blank].

==== NUMERIC

* POWER
* ABS
* MOD
* SQRT
* LN
* LOG10
* EXP
* CEIL
* FLOOR
* RAND
* ACOS
* ASIN
* ATAN
* ATAN2
* CBRT
* COS
* COT
* DEGREES
* PI()
* RADIANS
* ROUND
* SIGN
* SIN
* TAN
* TRUNCATE
* CHR
* COSH
* SINH
* TANH
* For more information on functions supported by Apache Calcite, see the link:https://calcite.apache.org/docs/reference.html#operators-and-functions[product documentation,window=_blank].

==== GENERAL

* NULLIF
* COALESCE
* CAST
* NVL
* GREATEST
* For more information on functions supported by Apache Calcite, see the link:https://calcite.apache.org/docs/reference.html#operators-and-functions[product documentation,window=_blank].


==== TIMESTAMP

* TIMESTAMP_ADD
* TIMESTAMP_DIFF
* EXTRACT
* LAST_DAY
* For more information on functions supported by Apache Calcite, see the link:https://calcite.apache.org/docs/reference.html#operators-and-functions[product documentation,window=_blank].