/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: local_file_meta.proto

package org.apache.ignite.raft.jraft.entity;

import org.apache.ignite.internal.network.annotations.Transferable;
import org.apache.ignite.raft.jraft.RaftMessageGroup;
import org.apache.ignite.raft.jraft.rpc.Message;
import org.jetbrains.annotations.Nullable;

public final class LocalFileMetaOutter {
    /**
     * Protobuf enum {@code jraft.FileSource}
     */
    public enum FileSource {
        /**
         * <code>FILE_SOURCE_LOCAL = 1;</code>
         */
        FILE_SOURCE_LOCAL(1),
        /**
         * <code>FILE_SOURCE_REFERENCE = 2;</code>
         */
        FILE_SOURCE_REFERENCE(2);

        public final int getNumber() {
            return value;
        }

        public static FileSource forNumber(int value) {
            switch (value) {
                case 1:
                    return FILE_SOURCE_LOCAL;
                case 2:
                    return FILE_SOURCE_REFERENCE;
                default:
                    return null;
            }
        }

        private final int value;

        private FileSource(int value) {
            this.value = value;
        }
    }

    @Transferable(value = RaftMessageGroup.RaftOutterMessageGroup.LOCAL_FILE_META)
    public interface LocalFileMeta extends Message {
        int sourceNumber();

        @Nullable
        default FileSource source() {
            return FileSource.forNumber(sourceNumber());
        }

        @Nullable
        String checksum();

        byte @Nullable[] userMeta();
    }
}
