/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Apache.Ignite.Internal.Generators
{
    using System;
    using System.IO;
    using System.Reflection;
    using Microsoft.CodeAnalysis;

    /// <summary>
    /// Generates source for ErrorGroups.
    /// </summary>
    [Generator]
    public sealed class ErrorGroupGenerator : ISourceGenerator
    {
        /// <inheritdoc/>
        public void Initialize(GeneratorInitializationContext context)
        {
            // No-op.
        }

        /// <inheritdoc/>
        public void Execute(GeneratorExecutionContext context)
        {
            var javaErrorGroupsFile = Path.GetFullPath(
                Path.Combine(
                    Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)!,
                    "..", // netcoreapp
                    "..", // Debug/Release
                    "..", // bin
                    "..", // Apache.Ignite.Internal.Generators
                    "..", // dotnet
                    "..", // platforms
                    "core",
                    "src",
                    "main",
                    "java",
                    "org",
                    "apache",
                    "ignite",
                    "lang",
                    "ErrorGroups.java"));

            if (!File.Exists(javaErrorGroupsFile))
            {
                throw new Exception("File not found: " + javaErrorGroupsFile);
            }

            var javaErrorGroupsText = File.ReadAllText(javaErrorGroupsFile);
            var source = $@"// <auto-generated/>
namespace Apache.Ignite
{{
    public static partial class ErrorGroup
    {{
        /// <summary> Transaction errors. </summary>
        public static class Transactions
        {{
            /// <summary> Group code. </summary>
            public const int GroupCode = 7;
        }}
    }}
}}";

            context.AddSource("ErrorGroup.g.cs", source);
        }
    }
}
