/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cli.proto

package com.alipay.sofa.jraft.rpc;

public final class CliRequests {
    public interface AddPeerRequest extends Message {
        java.lang.String getGroupId();

        java.lang.String getLeaderId();

        java.lang.String getPeerId();

        interface Builder {
            Builder setGroupId(String groupId);

            Builder setLeaderId(String leaderId);

            Builder setPeerId(String peerId);

            AddPeerRequest build();
        }

        public static Builder newBuilder() {
            return MessageBuilderFactory.DEFAULT.createAddPeer();
        }
    }

    public interface AddPeerResponse extends HasErrorResponse {
        static Message getDefaultInstance() {
            return null;
        }

        static Builder newBuilder() {
            return null;
        }

        java.util.List<java.lang.String> getOldPeersList();

        int getOldPeersCount();

        java.lang.String getOldPeers(int index);

        java.util.List<java.lang.String> getNewPeersList();

        int getNewPeersCount();

        java.lang.String getNewPeers(int index);

        RpcRequests.ErrorResponse getErrorResponse();

        public interface Builder {
            Builder addOldPeers(String oldPeersId);

            Builder addNewPeers(String newPeersId);

            AddPeerResponse build();
        }
    }

    public interface RemovePeerRequest extends Message {
        java.lang.String getGroupId();

        java.lang.String getLeaderId();

        java.lang.String getPeerId();

        interface Builder {
            Builder setGroupId(String groupId);

            Builder setLeaderId(String leaderId);

            Builder setPeerId(String peerId);

            RemovePeerRequest build();
        }

        public static Builder newBuilder() {
            return null;
        }
    }

    public interface RemovePeerResponse extends HasErrorResponse {
        static Message getDefaultInstance() {
            return null;
        }

        static Builder newBuilder() {
            return null;
        }

        /**
         * <code>repeated string old_peers = 1;</code>
         */
        java.util.List<java.lang.String> getOldPeersList();

        /**
         * <code>repeated string old_peers = 1;</code>
         */
        int getOldPeersCount();

        /**
         * <code>repeated string old_peers = 1;</code>
         */
        java.lang.String getOldPeers(int index);

        /**
         * <code>repeated string new_peers = 2;</code>
         */
        java.util.List<java.lang.String> getNewPeersList();

        /**
         * <code>repeated string new_peers = 2;</code>
         */
        int getNewPeersCount();

        /**
         * <code>repeated string new_peers = 2;</code>
         */
        java.lang.String getNewPeers(int index);

        RpcRequests.ErrorResponse getErrorResponse();

        public interface Builder {
            Builder addOldPeers(String oldPeerId);

            Builder addNewPeers(String newPeerId);

            RemovePeerResponse build();
        }
    }

    public interface ChangePeersRequest extends Message {
        /**
         * <code>required string group_id = 1;</code>
         */
        java.lang.String getGroupId();

        /**
         * <code>required string leader_id = 2;</code>
         */
        java.lang.String getLeaderId();

        /**
         * <code>repeated string new_peers = 3;</code>
         */
        java.util.List<java.lang.String> getNewPeersList();

        /**
         * <code>repeated string new_peers = 3;</code>
         */
        int getNewPeersCount();

        /**
         * <code>repeated string new_peers = 3;</code>
         */
        java.lang.String getNewPeers(int index);

        public interface Builder {
            Builder setGroupId(String groupId);

            Builder setLeaderId(String leaderId);

            Builder addNewPeers(String peerId);

            ChangePeersRequest build();
        }

        public static Builder newBuilder() {
            return null;
        }
    }

    public interface ChangePeersResponse extends HasErrorResponse {

        static Message getDefaultInstance() {
            return null;
        }

        static Builder newBuilder() {
            return null;
        }

        /**
         * <code>repeated string old_peers = 1;</code>
         */
        java.util.List<java.lang.String> getOldPeersList();

        /**
         * <code>repeated string old_peers = 1;</code>
         */
        int getOldPeersCount();

        /**
         * <code>repeated string old_peers = 1;</code>
         */
        java.lang.String getOldPeers(int index);

        /**
         * <code>repeated string new_peers = 2;</code>
         */
        java.util.List<java.lang.String> getNewPeersList();

        /**
         * <code>repeated string new_peers = 2;</code>
         */
        int getNewPeersCount();

        /**
         * <code>repeated string new_peers = 2;</code>
         */
        java.lang.String getNewPeers(int index);

        /**
         * <code>optional .jraft.ErrorResponse errorResponse = 99;</code>
         */
        RpcRequests.ErrorResponse getErrorResponse();

        public interface Builder {
            Builder addOldPeers(String oldPeerId);

            Builder addNewPeers(String newPeerId);

            ChangePeersResponse build();
        }
    }

    public interface SnapshotRequest extends Message {
        java.lang.String getGroupId();

        java.lang.String getPeerId();

        public interface Builder {
            Builder setGroupId(String groupId);

            Builder setPeerId(String peerId);

            SnapshotRequest build();
        }

        static Builder newBuilder() {
            return null;
        }
    }

    public interface ResetPeerRequest extends Message {
        java.lang.String getGroupId();

        java.lang.String getPeerId();

        java.util.List<java.lang.String> getOldPeersList();

        int getOldPeersCount();

        java.lang.String getOldPeers(int index);

        java.util.List<java.lang.String> getNewPeersList();

        int getNewPeersCount();

        java.lang.String getNewPeers(int index);

        public interface Builder {
            Builder setGroupId(String groupId);

            Builder setPeerId(String peerId);

            Builder addNewPeers(String peerId);

            ResetPeerRequest build();
        }

        public static Builder newBuilder() {
            return null;
        }
    }

    public interface TransferLeaderRequest extends Message {
        java.lang.String getGroupId();

        java.lang.String getLeaderId();

        java.lang.String getPeerId();

        boolean hasPeerId();

        public interface Builder {
            Builder setGroupId(String groupId);

            Builder setLeaderId(String leaderId);

            Builder setPeerId(String peerId);

            TransferLeaderRequest build();
        }

        public static Builder newBuilder() {
            return null;
        }
    }

    public interface GetLeaderRequest extends Message {
        java.lang.String getGroupId();

        java.lang.String getPeerId();

        boolean hasPeerId();

        public interface Builder {
            Builder setGroupId(String groupId);

            Builder setPeerId(String peerId);

            GetLeaderRequest build();
        }

        public static Builder newBuilder() {
            return null;
        }
    }

    public interface GetLeaderResponse extends HasErrorResponse {
        static Message getDefaultInstance() {
            return null;
        }

        static Builder newBuilder() {
            return null;
        }

        java.lang.String getLeaderId();

        RpcRequests.ErrorResponse getErrorResponse();

        public interface Builder {
            GetLeaderResponse build();

            Builder setLeaderId(String leaderId);
        }
    }

    public interface GetPeersRequest extends Message {
        java.lang.String getGroupId();

        java.lang.String getLeaderId();

        boolean getOnlyAlive();

        boolean hasOnlyAlive();

        public interface Builder {
            Builder setGroupId(String groupId);

            Builder setLeaderId(String leaderId);

            Builder setOnlyAlive(boolean onlyGetAlive);

            GetPeersRequest build();
        }

        public static Builder newBuilder() {
            return null;
        }
    }

    public interface GetPeersResponse extends HasErrorResponse {
        static Message getDefaultInstance() {
            return null;
        }

        static Builder newBuilder() {
            return null;
        }

        java.util.List<java.lang.String> getPeersList();

        int getPeersCount();

        java.lang.String getPeers(int index);

        java.util.List<java.lang.String> getLearnersList();

        int getLearnersCount();

        java.lang.String getLearners(int index);

        RpcRequests.ErrorResponse getErrorResponse();

        public interface Builder {
            Builder addPeers(String peerId);

            Builder addLearners(String learnerId);

            GetPeersResponse build();
        }
    }

    public interface AddLearnersRequest extends Message {
        java.lang.String getGroupId();

        java.lang.String getLeaderId();

        java.util.List<java.lang.String> getLearnersList();

        int getLearnersCount();

        java.lang.String getLearners(int index);

        public interface Builder {
            Builder setGroupId(String groupId);

            Builder setLeaderId(String leaderId);

            Builder addLearners(String learnerId);

            AddLearnersRequest build();
        }

        static Builder newBuilder() {
            return null;
        }
    }

    public interface RemoveLearnersRequest extends Message {
        java.lang.String getGroupId();

        java.lang.String getLeaderId();

        java.util.List<java.lang.String> getLearnersList();

        int getLearnersCount();

        java.lang.String getLearners(int index);

        public interface Builder {
            Builder setGroupId(String groupId);

            Builder setLeaderId(String leaderId);

            Builder addLearners(String leaderId);

            RemoveLearnersRequest build();
        }

        static Builder newBuilder() {
            return null;
        }
    }

    public interface ResetLearnersRequest extends Message {
        java.lang.String getGroupId();

        java.lang.String getLeaderId();

        java.util.List<java.lang.String> getLearnersList();

        /**
         * <code>repeated string learners = 3;</code>
         */
        int getLearnersCount();

        /**
         * <code>repeated string learners = 3;</code>
         */
        java.lang.String getLearners(int index);

        public interface Builder {
            Builder setGroupId(String groupId);

            Builder setLeaderId(String leaderId);

            Builder addLearners(String learnerId);

            ResetLearnersRequest build();
        }

        static Builder newBuilder() {
            return null;
        }
    }

    public interface LearnersOpResponse extends HasErrorResponse {
        static Message getDefaultInstance() {
            return null;
        }

        java.util.List<java.lang.String> getOldLearnersList();

        int getOldLearnersCount();

        java.lang.String getOldLearners(int index);

        java.util.List<java.lang.String> getNewLearnersList();

        int getNewLearnersCount();

        java.lang.String getNewLearners(int index);

        RpcRequests.ErrorResponse getErrorResponse();

        static Builder newBuilder() {
            return null;
        }

        public interface Builder {
            Builder addOldLearners(String oldLearnersId);

            Builder addNewLearners(String newLearnersId);

            LearnersOpResponse build();
        }
    }
}
