// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Installing Using ZIP Archive

== Prerequisites

=== Recommended Operating System

include::includes/prereqs-os.adoc[]

=== Recommended Java Version

include::includes/prereqs-java.adoc[]

== Apache Ignite Package Structure

Apache Ignite provides 2 archives for the distribution:

- `ignite3-db-3.1.0` - this archive contains everything related to the Apache Ignite database. When unpacked, it creates the folder where data will be stored by default. You start Apache Ignite nodes from this folder.
- `ignite3-cli-3.1.0` - this archive contains the link:ignite-cli-tool[Apache Ignite CLI tool]. This tool is the main way of interacting with Apache Ignite clusters and nodes.

== Installing Apache Ignite Database

To install the Apache Ignite database, link:https://ignite.apache.org/download.cgi[download] the database archive from the website and then:

. Unpack the archive:
+
[tabs]
--
tab:Unix[]
[source,shell, subs="attributes,specialchars"]
----
unzip ignite3-db-3.1.0.zip && cd ignite3-db-3.1.0
----


tab:Windows (PowerShell)[]
[source,shell, subs="attributes,specialchars"]
----
Expand-Archive ignite3-3.1.0.zip -DestinationPath . ; cd ignite3-db-3.1.0
----

tab:Windows (CMD)[]
[source,shell, subs="attributes,specialchars"]
----
unzip -xf ignite3-db-3.1.0.zip & cd ignite3-db-3.1.0
----
--

. Create the `IGNITE_HOME` environment variable with the path to the `ignite3-db-3.1.0` folder.

== Starting the Node

Once you have unpacked the archive, you can start the Apache Ignite node:

[source,shell]
----
bin/ignite3db
----

By default, the node loads the `etc/ignite-config.conf` configuration file on startup. You can update it to customize the node configuration, or change the configuration folder in the `etc/vars.env` file.

When the node is started, it will enter the cluster if it is already configured and initialized, or will wait for cluster initialization.

== Installing Apache Ignite CLI Tool

The CLI tool is the primary means of working with the Apache Ignite database. It is not necessary to install on every machine that is running Apache Ignite, as you can connect to the node via REST interface.

To install the Apache Ignite CLI, link:https://ignite.apache.org/download.cgi[download] the database archive from the website and then unpack it:

[tabs]
--
tab:Unix[]
[source,shell, subs="attributes,specialchars"]
----
unzip ignite3-cli-3.1.0.zip && cd ignite3-cli-3.1.0
----


tab:Windows (PowerShell)[]
[source,shell, subs="attributes,specialchars"]
----
Expand-Archive ignite3-cli-3.1.0.zip -DestinationPath . ; cd ignite3-cli-3.1.0
----

tab:Windows (CMD)[]
[source,shell, subs="attributes,specialchars"]
----
unzip -xf ignite3-cli-3.1.0.zip & cd ignite3-cli-3.1.0
----
--

== Next Steps

With Apache Ignite installed, you can proceed with the link:quick-start/getting-started-guide[Getting Started] or link:developers-guide/table-api[use the available APIs] immediately.