// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Installing Using Docker

== Prerequisites

=== Recommended Docker Version

include::includes/prereqs-docker.adoc[]

=== Recommended Operating System

include::includes/prereqs-os.adoc[]

=== Recommended Java Version

include::includes/prereqs-java.adoc[]


== Running a Node

Run Apache Ignite in a docker container using the `docker run` command. Docker will automatically pull the appropriate Apache Ignite version:

[source,shell]
----
docker run -d -p 10300:10300 -p 10800:10800 -p 3344:3344 ignite/ignite3:latest
----

[NOTE]
====
If you plan to store persistent data, it is recommended to mount a volume for it. Otherwise, data will be deleted when the container is removed.

Consider storing the `/opt/ignite/work` folder to keep application data and persistent data.
====


This command launches a single Apache Ignite node. After you run the command, you can check if Apache Ignite is running in the container logs.

== Running a Cluster

You can use the docker-compose file to start an entire cluster in docker. You can download a sample docker-compose file and run a 3-node cluster:

- Download the link:quick-start/docker-compose.yml[docker-compose] file.
+
NOTE: Docker compose version 2.23.1 or later is required to use the provided compose file.
+
- Download the docker image:
+
[source,shell, subs="attributes,specialchars"]
----
docker pull apache/ignite3:3.1.0
----
+
- Run the docker compose command.
+
[source,shell]
----
docker compose -f docker-compose.yml up -d
----

3 nodes will start in Docker and will be available from the CLI tool that can be run locally. Remember to initialise the cluster from the command line tool before working with it.

== Running CLI Tool in Docker

NOTE: It is not recommended to run the CLI tool in docker. Instead, we recommend to link:installation/installing-using-zip[download and install] CLI tool locally.

CLI tool is used to manage Apache Ignite nodes.  By default, docker nodes are isolated and run on different networks, so CLI tool will not be able to connect to the target container from another container. To fix that, you need to create a network and add all containers running the nodes to it.

- Create a new network with the `network create` command:
+
----
docker network create ignite-network
----
+
- Add any containers with nodes that are already running to the network:
+
----
docker network connect ignite-network {container-id}
----
+
- Start the container with the Apache Ignite CLI tool on the same network:
+
[source,shell, subs="attributes,specialchars"]
----
docker run -p 10301:10300 -p 10801:10800 -p 3345:3344 -it --network=ignite-network apache/ignite3:3.1.0 cli
----
+
[TIP]
====
You may need to mount configuration or data files. To provide them, mount the files you will use, for example:
+
[source, text, subs="attributes,specialchars"]
----
docker run --rm -it --network=host -v /opt/etc/config.conf:/opt/ignite/etc/ignite-config.conf apache/ignite3:3.1.0 cli
----
====

The CLI will be able to connect to the IP address of the node. If you are not sure what the address is, use the `container inspect` command to check it:

----
docker container inspect {container-id}
----


