// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Data Region Configuration

You can set configuration for data regions by using HOCON format. You can configure your data regions to run either RocksDB or B+Tree storage, and fine-tune their performance. A cluster can have several data regions, and you can select the preferred storage type for each. Configuration parameters for data regions are available in the storage-related articles.

We recommend to use B+Tree storage for read-heavy workloads, and RocksDB for write-heavy workloads.


== Configuration Example

The example below shows how to configure two data regions, one using RocksDB storage, and another using a volatile page memory:

----
ignite config set --type cluster \
"{
    rocksdb.regions: [{
        name: lsm_region,
        size: 256000000
    }],

    aimem.regions: [{
        name: btree_volatile_region,
        maxSize: 256000000
    }]
}"
----
