/'
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
'/

@startuml
title Accepting an update

autonumber

actor User

activate User
User -> CatalogManager ++ : Create table (CreateTableCommand)
CatalogManager -> CatalogManager : Acquire latest catalog version
CatalogManager -> CatalogManager : Calculates incremental updates by applying provided command
CatalogManager -> UpdateLog -- : Saves diffs to update log under latestVersion+1
UpdateLog --> CatalogManager ++
CatalogManager -> CatalogManager --++ : Wait catalog of new version to appear in local cache

alt updates were saved

  CatalogManager -> CatalogManager --++ : Wait for delay duration
  CatalogManager -> User -- : Success (Completes the future successfully)

else updates were not saved because of concurrent update

  alt retry limit is not exceeded

    CatalogManager -> CatalogManager : Restart from p.2

  else retry limit is exceeded

    CatalogManager -> User -- : Failure (Completes future exceptionally)

  end

end

deactivate User
@enduml