/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: local_storage.proto

package com.alipay.sofa.jraft.entity;

public final class LocalStorageOutter {
    public interface ConfigurationPB {
        java.util.List<java.lang.String> getPeersList();

        int getPeersCount();

        java.lang.String getPeers(int index);

        java.util.List<java.lang.String> getOldPeersList();

        int getOldPeersCount();

        java.lang.String getOldPeers(int index);
    }

    public interface LogPBMeta {
        long getFirstLogIndex();
    }

    public interface StablePBMeta {
        long getTerm();

        java.lang.String getVotedfor();
    }

    public interface LocalSnapshotPbMeta {
        com.alipay.sofa.jraft.entity.RaftOutter.SnapshotMeta getMeta();

        java.util.List<com.alipay.sofa.jraft.entity.LocalStorageOutter.LocalSnapshotPbMeta.File> getFilesList();

        int getFilesCount();

        com.alipay.sofa.jraft.entity.LocalStorageOutter.LocalSnapshotPbMeta.File getFiles(int index);

        interface File {
            java.lang.String getName();

            LocalFileMetaOutter.LocalFileMeta getMeta();
        }
    }
}
