#!/bin/sh

#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
set -o errexit # Exit on error
set -o nounset # Exit on unset variables

SCRIPT_DIR=$(dirname "$0")

cd ${SCRIPT_DIR} || exit  # SCRIPT_DIR points at bin
cd .. # now SCRIPT_DIR points at parent dir for bin

# if IGNITE_HOME is not set than it will be parent directory for bin
if [ -z ${IGNITE_HOME+x} ]; then IGNITE_HOME=$(pwd); fi

. @CONF_DIR@/@VARS_FILE_NAME@
. ${LIBS_DIR}/@BOOTSTRAP_FILE_NAME@

cd ${IGNITE_HOME} || exit

CMD="${JAVA_CMD_WITH_ARGS} ${APPLICATION_ARGS}"
$CMD
