import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Apache Ignite 3 Documentation Sidebar Configuration
 *
 * Sidebars are generated from the docs folder structure.
 * Manual configuration can be added as content is migrated from Jekyll.
 */
const sidebars: SidebarsConfig = {
  // Documentation sidebar - autogenerated from docs folder
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
