name: Code Quality Checks

on:
  workflow_run:
    workflows: [ "Build" ]
    types: [ completed ]

jobs:
  checks:
    name: Checkstyle, PMD, SpotBugs
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest checkstyleIntegrationTest checkstyleTestFixtures

      - name: Run PMD
        if: success() || failure()
        run: ./gradlew pmdMain pmdTest pmdIntegrationTest pmdTestFixtures

      - name: Run SpotBugs
        if: success() || failure()
        run: ./gradlew spotbugsMain spotbugsTest spotbugsIntegrationTest spotbugsTestFixtures
