name: "Build pyignite-dbapi Mac wheels"

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    paths:
      - 'modules/platforms/python/**.py'
      - 'modules/platforms/cpp/**'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        #os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        os: [macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.23.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir modules/platforms/python/wheels modules/platforms/python
        env:
          CIBW_BUILD: cp39-* cp310-* cp311-* cp312-* cp313-*

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: modules/platforms/python/wheels/*.whl

