// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Cluster and Node Configuration

//NOTE:UPDATE WITH SPECIFIC PARAMS FOR PUBLIC RELEASE

In Ignite 3, configuration is performed by using the link:ignite-cli-tool[CLI utility]. Ignite 3 configuration is stored in HOCON format. You can manage and configure parameters at any point during cluster runtime and during cluster startup.

== Updating Configuration from CLI

=== Getting Cluster and Node Configuration

You can get cluster configuration by using the `cluster config show`, and the configuration of the node you are connected to by using the `node config show` command.

=== Updating Cluster and Node Configuration

You can update the configuration by using the `cluster config update` and `node config update` commands and passing the new valid HOCON string as the parameter. Below are some examples of updating the configuration:

==== Updating a single parameter

Updating a single parameter is done by specifying the parameter and assigning it a new value:

----
node config update network.shutdownTimeout=20000
----

==== Updating Multiple Parameters

When updating multiple parameters at once, pass the valid HOCON configuration to Ignite. The CLI tool will then parse it and apply all required change at the same time.

----
cluster config update "{security.authentication.providers:[{name:basic,password:admin_password,type:basic,username:admin_user,roles:[admin]}],security.authentication.enabled:true}"
----

== Configuration Files

When a Ignite node starts, it reads its starting configuration from the `etc/ignite-config.conf` file.  You can change the file to always consistently start a node with specified configuration.

Cluster configuration is stored on the cluster nodes, and is shared to all nodes in cluster automatically. You should use the CLI tool to manage this configuration.

Ignite also uses a number of environmental parameters to define properties not related to node or cluster operations. When a node starts, it loads these parameters from the `etc/vars.env` file. Edit this file to configure locations of work-related folders, JVM properties and additional JVM arguments through the `IGNITE3_EXTRA_JVM_ARGS` parameter.
